[package]
name = "pairswitch"
version = "0.1.0"
authors = ["Mark Cipolla <mark@markcipolla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.4.1"
structopt = "0.3.13"
